name: build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: app_build
    image: python:3.8-slim-busters
    run: "python <<< "print('Hello')""

name: test
on:
  push:
    branches:
      - dev
  jobs:
    test:
      name: test app
      image: python:3.8-slim-busters
      run: "python <<< "print('Hello')""
